services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    depends_on:
      - postgres
      - redis

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - web-static:/usr/src/app/static
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata: